### ISSUE TITLE
Readme を追加する

### ISSUE THREAD

**Issue by shundroid** [comozilla/comozilla-paper#6]

**Comment by mk7087** [comment]
> Readmeを追加する

ではなく
Lisenseを追加する

**Comment by shundroid** [comment]
@mk7087 
いや、Readme であってるよ

**Comment by mk7087** [comment]
Readmeファイルは作ってはいないよ
LISECEファイルは追加したけど

**Comment by shundroid** [comment]
@mk7087 そうそう、この Issue ってのはやったことじゃなくてこれからやることをかくから、
これから「Readmeファイルを追加する」ってことです。

ほかの３つの Issue も同様です

**Comment by mk7087** [comment]
何を書くのかわからない

**Comment by shundroid** [comment]
@mk7087 

https://github.com/comozilla/onigo-controller/blob/master/readme.md
こういうの

https://raw.githubusercontent.com/comozilla/onigo-controller/master/readme.md
内容はこうやって Markdown で書く。

もしわかんなかったら、これは今度会ったときに説明するね
ほかにも Issue があるから、そっちをやってみてもいいかも

**Comment by shundroid** [comment]
@mk7087 Issue が解決したから Close するね
